var util=require("util");Creep.prototype.add_task=function(b){this.memory.task_queue||(this.memory.task_queue=[]);this.memory.task_queue.unshift(b)};Creep.prototype.pop_task=function(){this.memory.task_queue.shift()};Creep.prototype.renew_cost=function(){return floor(600/this.body.length)};Creep.prototype.body_cost=function(){this.body.forEach(function(b){bodY_list.push(b.type)});return util.body_cost([])};
Room.prototype.scout_room=function(){this.memory.intel={};var b=this.memory.intel;b.time_scouted=Game.time;b.sources={};this.find(FIND_SOURCES).forEach(function(a){b.sources[a.id]={pos:a.pos}});b.minerals={};this.find(FIND_MINERALS).forEach(function(a){b.minerals[a.id]={pos:a.pos,type:a.mineralType,amount:a.mineralAmount,ticksToRegeneration:a.ticksToRegeneration}});this.controller?(b.controller={},b.controller.level=this.controller.level,b.controller.owner=this.controller.owner,b.controller.reservation=
this.controller.reservation,b.controller.id=this.controller.id):b.controller=null;b.structure_maintain_cost=0;this.find(FIND_STRUCTURES).forEach(function(a){b.structure_maintain_cost+=a.maintain_cost()});b.creep_maintain_cost=0;this.find(FIND_CREEPS).forEach(function(a){b.creep_maintain_cost+=a.maintain_cost()})};Structure.prototype.getMemory=function(){var b=Memory.structures[this.id];if(b)return b;Memory.structures[this.id]={};return Memory.structures[this.id]};
Structure.prototype.add_task=function(b){var a=this.getMemory();a.task_queue||(a.task_queue=[]);a.task_queue.unshift(b)};Structure.prototype.pop_task=function(){this.getMemory().task_queue.shift()};
module.exports={harvest:function(b,a){if(a.carryCapacity==a.carry.energy)return{outcome:"didnothing"};var c=Game.getObjectById(b.selected_source_id);if(!c&&(c=a.pos.findClosestByRange(FIND_SOURCES)))b.selected_source_id=c.id;return!c?(a.say("!sr?:("),{outcome:"newtask",task:{type:"resupply"}}):a.harvest(c)==ERR_NOT_IN_RANGE?(a.moveTo(c),{outcome:"continue"}):a.carryCapacity==a.carry.energy?{outcome:"done"}:{outcome:"continue"}},construct:function(b,a){var c=b.resupply,d=Game.getObjectById(b.target_id);
if(!d)return a.say("cs ?!?"),{outcome:"didnothing"};if(0==a.carry.energy)return c?{outcome:"newtask",task:{type:c}}:{outcome:"didnothing"};if("undefined"==typeof d.progress){if(d.hits==d.hitsMax)return{outcome:"didnothing"};c=a.repair(d)}else c=a.build(d);c==ERR_NOT_IN_RANGE&&a.moveTo(d);return{outcome:"continue"}},resupply:function(b,a){var c=a.carryCapacity-a.carry.energy;if(0==c)return{outcome:"didnothing"};var d=Game.getObjectById(b.gas_station_id);if(!d){var e=a.room.find(FIND_STRUCTURES,{filter:function(a){return a.structureType!=
STRUCTURE_CONTAINER?!1:a.store[RESOURCE_ENERGY]>c}});e.length&&(d=a.pos.findClosestByRange(e),b.gas_station_id=d.id)}if(!d)return{outcome:"replace",task:{type:"harvest"}};e=a.withdraw(d,RESOURCE_ENERGY);return e==ERR_NOT_IN_RANGE?(a.moveTo(d),{outcome:"continue"}):e==ERR_NOT_ENOUGH_RESOURCES?(b.gas_station_id=null,{outcome:"continue"}):e!=OK?(a.say("rs!"+e),{outcome:"continue"}):{outcome:"done"}},renew:function(b,a){if(1400<=a.ticksToLive)return{outcome:"done"};var c=Game.getObjectById(b.spawn_id);
if(!c&&(c=a.pos.findClosestByRange(FIND_MY_SPAWNS)))b.spawn_id=c.id;if(!c)return a.say("SPN?!?"),{outcome:"done"};var d=c.renewCreep(a);a.transfer(c,RESOURCE_ENERGY);if(d==ERR_NOT_IN_RANGE)a.moveTo(c);else if(d==ERR_FULL||d==ERR_NOT_ENOUGH_ENERGY)return{outcome:"done"};return{outcome:"continue"}},transfer_energy:function(b,a){target=Game.getObjectById(b.target_id);if(!target||target.energy==target.energyCapacity||0==a.carry.energy)return{outcome:"didnothing"};switch(a.transfer(target,RESOURCE_ENERGY)){case ERR_NOT_IN_RANGE:a.moveTo(target);
break;case ERR_FULL:if(b.dump_excess_on_target)if(a.pos!=target.pos){a.moveTo(target);break}else return a.drop(RESOURCE_ENERGY),{outcome:"done"};case ERR_INVALID_TARGET:return{outcome:"didnothing"};case OK:return{outcome:"done"}}return{outcome:"continue"}},tower_target:function(b,a){target=Game.getObjectById(b.target_id);mode=b.mode;if(!mode||!target||b.times_run&&25<b.times_run)return{outcome:"didnothing"};var c;switch(mode){case "heal":if(target.hits==target.hitsMax)return{outcome:"didnothing"};
c=a.heal(target);break;case "repair":if(target.hits==target.hitsMax)return{outcome:"didnothing"};c=a.repair(target);break;case "attack":c=a.attack(target)}switch(c){case ERR_INVALID_TARGET:case ERR_RCL_NOT_ENOUGH:return{outcome:"didnothing"};case OK:case ERR_NOT_ENOUGH_RESOURCES:return{outcome:"continue"}}},dismantle:function(b,a){var c=Game.getObjectById(b.target_id);if(!c)return{outcome:"didnothing"};if(a.carry.energy==a.carryCapacity){var d=a.pos.findStructures(STRUCTURE_CONTAINER);if(d=a.pos.findClosestByPath(d))return b=
{type:"transfer_energy",target_id:d.id,dump_excess_on_target:!0},{outcome:"newtask",task:b};a.drop(RESOURCE_ENERGY)}switch(a.dismantle(c)){case ERR_NOT_IN_RANGE:return a.moveTo(c),{outcome:"continue"};case OK:return{outcome:"done"};default:return{outcome:"didnothing"}}},run_task_queue:function(b,a){for(;a&&a.length;){var c=a[0];"undefined"==typeof c.times_run&&(c.times_run=0);var d=b.say||function(a){},e=(0,module.exports[c.type])(c,b);if(e)if("done"==e.outcome)b.pop_task();else if("continue"==e.outcome)c.times_run++;
else if("newtask"==e.outcome)c.times_run++,b.add_task(e.task);else if("replace"==e.outcome)b.pop_task(),b.add_task(e.task);else if("didnothing"==e.outcome){b.pop_task();continue}else d("?"+e.outcome),b.pop_task();else d("!octq"),b.pop_task();break}}};
