#!/usr/bin/env python
# Oh the magic of pre-commiting.

import os
import sys
import os.path
import subprocess
import shutil

check_only = True

for dirpath, dirnames, filenames in os.walk('.'):
    for name in filenames:
        if not name.endswith('.screeps'):
            continue
        full_name = os.path.join(dirpath, name)
        js_name = full_name.replace(".screeps", ".js")
        fmt = "Closure Compiler{} ({} -> {})"
        if check_only:
            check_msg = " (CHECK ONLY)"
        else:
            check_msg = ""
        print(fmt.format(check_msg, full_name, js_name))
        args = ["closure-compiler", "--js", full_name, "--js_output_file"]
        if check_only:
            args.append("/dev/null")
        else:
            args.append(js_name)
        subprocess.call(args)
        if check_only:
            shutil.copy(full_name, js_name)

        subprocess.call(["git","add",js_name])
