#!/usr/bin/env python
# Oh the magic of pre-commiting.

import os
import sys
import os.path
import subprocess
import shutil

check_only = False

for dirpath, dirnames, filenames in os.walk('.'):
    for name in filenames:
        if not name.endswith('.screeps'):
            continue
        full_name = os.path.join(dirpath, name)
        js_name = full_name.replace(".screeps", ".js")

        try:
            full_stats = os.stat(full_name)
            js_stats = os.stat(js_name)
        except OSError:
            pass
        else:
            if full_stats.st_mtime <= js_stats.st_mtime:
                print("{} is up to date".format(full_name))
                continue

        fmt = "Closure Compiler{} ({} -> {})"
        if check_only:
            check_msg = " (CHECK ONLY)"
        else:
            check_msg = ""
        print(fmt.format(check_msg, full_name, js_name))
        args = ["closure-compiler", "--js", full_name]
        if check_only:
            pass
        else:
            args.extend(["--js_output_file", js_name])
        rc = subprocess.call(args)
        if rc == 0:
            if check_only:
                shutil.copyfile(full_name, js_name)

            subprocess.call(["git","add",js_name])
